id: ICCCC8C28
ocr_import_info:
  source: bdrc
  software: google_books
  batch: batch_2022
  expected_default_language: bo
  bdrc_scan_id: W3CN1837
  ocr_info:
    timestamp: 03/21/23T14:17:10
    html: html.zip
    txt: txt.zip
    images: images.zip
  op_import_options: {}
  op_import_version: 0.11.9
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2024-02-28 23:11:59.046828+00:00
last_modified: 2024-02-28 23:11:59.046837+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN1837
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN1837
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བདེ་མཆོག་ལྷ་ལྔའི་སྒྲུབ་ཐབས་སོགས་ཆོས་ཚན་ལྔ་།
  languages:
  - bo
  author: ཏཱ་ལའི་བླ་མ ༠༢་དགེ་འདུན་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.9458753202391119
  ocr_word_median_confidence_index: 1.0
bases:
  I3CN1839:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN1839
      total_pages: 136
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN1839.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9458753202391119
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
